export const inputsClass = "flex flex-row rounded border-2 border-gray-200 hover:cursor-pointer hover:border-lime"
export const inputsErrorClass = inputsClass + " " + "border-red hover:border-red hover:border-orange-600"
export const inputsLogo = "bg-sky-100 text-gray-400 text-sm font-semibold w-auto text-center py-2 px-3"
export const inputsLogoError = "bg-red text-white text-sm font-semibold w-auto text-center py-2 px-3"
export const radioLabels = "mb-2 inline-flex items-cente border-2 min-w-full p-2 pl-3 rounded border-gray-200 hover:border-lime hover:cursor-pointer"
export const radioSelectedLabel = "mb-2 inline-flex items-cente border-2 min-w-full p-2 pl-3 rounded border-lime hover:cursor-pointer bg-orange-100"